"""add categories

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 10:45:00.000000
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None

# Snapshot figé des catégories prédéfinies au moment de cette migration : ne pas importer
# app.seed.DEFAULT_CATEGORIES ici, sous peine de rejouer une liste différente si elle évolue.
DEFAULT_CATEGORIES = [
    {"name": "Produits laitiers", "emoji": "🥛", "default_expiry_days": 7},
    {"name": "Viande", "emoji": "🥩", "default_expiry_days": 3},
    {"name": "Poisson", "emoji": "🐟", "default_expiry_days": 2},
    {"name": "Légumes", "emoji": "🥦", "default_expiry_days": 7},
    {"name": "Fruits", "emoji": "🍎", "default_expiry_days": 7},
    {"name": "Boulangerie", "emoji": "🍞", "default_expiry_days": 4},
    {"name": "Conserves", "emoji": "🥫", "default_expiry_days": 365},
    {"name": "Surgelés", "emoji": "🧊", "default_expiry_days": 180},
    {"name": "Boissons", "emoji": "🥤", "default_expiry_days": 30},
    {"name": "Restes", "emoji": "🍱", "default_expiry_days": 3},
    {"name": "Autre", "emoji": "📦", "default_expiry_days": 7},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column("default_expiry_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("default_expiry_days > 0", name="ck_categories_expiry_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    op.create_index(
        "uq_categories_user_name_lower",
        "categories",
        ["user_id", sa.text("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###

    categories = sa.table(
        "categories",
        sa.column("user_id", sa.Integer()),
        sa.column("name", sa.String()),
        sa.column("emoji", sa.String()),
        sa.column("default_expiry_days", sa.Integer()),
    )
    op.bulk_insert(
        categories,
        [{"user_id": None, **category} for category in DEFAULT_CATEGORIES],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_categories_user_name_lower", table_name="categories")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
